version: '3'
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    ports: 
      - "1234:1234"
  web:
    image: express-wt18-hf-rm-tj
    build: ./
    command: node server.js
    ports:
      - "8081:8081"
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
